
const vocabulary = [
	{ es: 'el', description: 'artículo determinativo', level: 2, theme: 'gramática' },
	{ es: 'de', description: 'preposición de genitivo', level: 1, theme: 'gramática' },
	{ es: 'que', description: 'conjunción de subordinación', level: 3, theme: 'gramática' },
	{ es: 'y', description: 'conjunción copulativa', level: 2, theme: 'gramática' },
	{ es: 'a', description: 'preposición de dirección', level: 1, theme: 'gramática' },
	{ es: 'en', description: 'preposición de lugar', level: 2, theme: 'gramática' },
	{ es: 'un', description: 'artículo indeterminado', level: 2, theme: 'gramática' },
	{ es: 'ser', description: 'verbo "ser"', level: 4, theme: 'verbos' },
	{ es: 'se', description: 'pronombre reflexivo', level: 3, theme: 'gramática' },
	{ es: 'no', description: 'adverbio de negación', level: 2, theme: 'gramática' },
	{ es: 'rojo', description: 'color', level: 3, theme: 'colores' },
	{ es: 'casa', description: 'vivienda', level: 2, theme: 'hogar' },
	{ es: 'mesa', description: 'mueble', level: 2, theme: 'hogar' },
	{ es: 'gato', description: 'animal', level: 2, theme: 'animales' },
	{ es: 'sol', description: 'sole', level: 2, theme: 'natura' },
	{ es: 'playa', description: 'spiaggia', level: 3, theme: 'luoghi' },
	{ es: 'árbol', description: 'albero', level: 2, theme: 'natura' },
	{ es: 'mar', description: 'mare', level: 3, theme: 'natura' },
	{ es: 'montaña', description: 'montagna', level: 4, theme: 'natura' },
	{ es: 'guitarra', description: 'chitarra', level: 4, theme: 'strumenti musicali' },
	{ es: 'pintura', description: 'pittura', level: 3, theme: 'arte' },
	{ es: 'música', description: 'musica', level: 2, theme: 'arte' },
	{ es: 'libro', description: 'libro', level: 2, theme: 'lettura' },
	{ es: 'café', description: 'caffè', level: 2, theme: 'bevande' },
	{ es: 'comida', description: 'cibo', level: 2, theme: 'cucina' },
	{ es: 'amor', description: 'amore', level: 3, theme: 'emozioni' },
	{ es: 'tiempo', description: 'tempo', level: 2, theme: 'concetto' },
	{ es: 'felicidad', description: 'felicità', level: 4, theme: 'emozioni' },
	{ es: 'viaje', description: 'viaggio', level: 3, theme: 'esperienze' },
	{ es: 'amigo', description: 'amico', level: 2, theme: 'relazioni' },
	{ es: 'fiesta', description: 'festa', level: 3, theme: 'celebrazioni' },
	{ es: 'deporte', description: 'sport', level: 3, theme: 'attività fisica' },
	{ es: 'película', description: 'film', level: 3, theme: 'intrattenimento' },
	{ es: 'risa', description: 'risata', level: 2, theme: 'emozioni' },
	{ es: 'efímero', description: 'effimero', level: 8, theme: 'concetto' },
	{ es: 'ambivalencia', description: 'ambivalenza', level: 7, theme: 'emozioni' },
	{ es: 'perplejidad', description: 'perplessità', level: 7, theme: 'emozioni' },
	{ es: 'idiosincrasia', description: 'idiosincrasia', level: 9, theme: 'concetto' },
	{ es: 'procrastinación', description: 'procrastinazione', level: 8, theme: 'comportamento' },
	{ es: 'enigmático', description: 'enigmatico', level: 8, theme: 'concetto' },
	{ es: 'apoteosis', description: 'apoteosi', level: 9, theme: 'concetto' },
	{ es: 'melancolía', description: 'malinconia', level: 7, theme: 'emozioni' },
	{ es: 'paradigma', description: 'paradigma', level: 8, theme: 'concetto' },
	{ es: 'inefable', description: 'ineffabile', level: 9, theme: 'concetto' },
	{ es: 'paradoja', description: 'paradosso', level: 8, theme: 'concetto' },
	{ es: 'inexorable', description: 'inesorabile', level: 9, theme: 'concetto' },
	{ es: 'estratagema', description: 'stratagemma', level: 8, theme: 'concetto' },
	{ es: 'iridiscente', description: 'iridescente', level: 7, theme: 'natura' },
	{ es: 'espontáneo', description: 'spontaneo', level: 6, theme: 'carattere' },
	{ es: 'quimera', description: 'chimera', level: 8, theme: 'mitologia' },
	{ es: 'meticuloso', description: 'meticoloso', level: 6, theme: 'carattere' },
	{ es: 'efervescente', description: 'effervescente', level: 7, theme: 'natura' },
	{ es: 'prolijo', description: 'pignolo', level: 6, theme: 'carattere' },
	{ es: 'indómito', description: 'indomito', level: 7, theme: 'carattere' },
	{ es: 'sutil', description: 'sottile', level: 5, theme: 'concetto' },
	{ es: 'arduo', description: 'arduo', level: 6, theme: 'concetto' },
	{ es: 'peregrino', description: 'pellegrino', level: 5, theme: 'persona' },
	{ es: 'prolijo', description: 'prolijo', level: 6, theme: 'concetto' },
	{ es: 'pretensión', description: 'pretesa', level: 5, theme: 'concetto' },
	{ es: 'inefable', description: 'ineffabile', level: 6, theme: 'concetto' },
	{ es: 'desidia', description: 'indolenza', level: 5, theme: 'carattere' },
	{ es: 'abrumador', description: 'opprimente', level: 6, theme: 'concetto' },
	{ es: 'magnánimo', description: 'magnanimo', level: 5, theme: 'carattere' },
	{ es: 'convicción', description: 'convizione', level: 6, theme: 'concetto' },
	{ es: 'obstinado', description: 'ostinato', level: 5, theme: 'carattere' },
	{ es: 'prosaico', description: 'prosaico', level: 6, theme: 'concetto' },
	{ es: 'empatía', description: 'empatia', level: 5, theme: 'concetto' },
	{ es: 'voraz', description: 'vorace', level: 6, theme: 'concetto' },
	{ es: 'insólito', description: 'insolito', level: 5, theme: 'concetto' },
	{ es: 'espontáneo', description: 'spontaneo', level: 6, theme: 'carattere' },
	{ es: 'irónico', description: 'ironico', level: 5, theme: 'concetto' },
	{ es: 'sobrio', description: 'sobrio', level: 6, theme: 'carattere' },
	{ es: 'pragmático', description: 'pragmatico', level: 5, theme: 'concetto' },
	{ es: 'deslumbrante', description: 'abbagliante', level: 6, theme: 'concetto' },
	{ es: 'efímero', description: 'effimero', level: 7, theme: 'concetto' },
	{ es: 'ambivalencia', description: 'ambivalenza', level: 7, theme: 'emozioni' },
	{ es: 'perplejidad', description: 'perplessità', level: 7, theme: 'emozioni' },
	{ es: 'idiosincrasia', description: 'idiosincrasia', level: 7, theme: 'concetto' },
	{ es: 'enigmático', description: 'enigmatico', level: 7, theme: 'concetto' },
	{ es: 'melancolía', description: 'malinconia', level: 7, theme: 'emozioni' },
	{ es: 'iridiscente', description: 'iridescente', level: 7, theme: 'natura' },
	{ es: 'quimera', description: 'chimera', level: 7, theme: 'mitologia' },
	{ es: 'indómito', description: 'indomito', level: 7, theme: 'carattere' },
	{ es: 'espléndido', description: 'splendido', level: 7, theme: 'concetto' },
	{ es: 'hipotético', description: 'ipotetico', level: 7, theme: 'concetto' },
	{ es: 'elocuente', description: 'eloquente', level: 7, theme: 'concetto' },
	{ es: 'perspicaz', description: 'perspicace', level: 7, theme: 'concetto' },
	{ es: 'efervescente', description: 'effervescente', level: 7, theme: 'natura' },
	{ es: 'intrínseco', description: 'intrinseco', level: 7, theme: 'concetto' },
	{ es: 'impávido', description: 'impavido', level: 7, theme: 'carattere' },
	{ es: 'efímera', description: 'effimera', level: 7, theme: 'concetto' },
	{ es: 'irrisorio', description: 'irrisorio', level: 7, theme: 'concetto' },
	{ es: 'oscuro', description: 'oscuro', level: 7, theme: 'concetto' },
	{ es: 'inmutable', description: 'inmutabile', level: 7, theme: 'concetto' },
	{ es: 'arduo', description: 'arduo', level: 6, theme: 'concetto' },
	{ es: 'prolijo', description: 'prolijo', level: 6, theme: 'concetto' },
	{ es: 'abrumador', description: 'opprimente', level: 6, theme: 'concetto' },
	{ es: 'magnánimo', description: 'magnanimo', level: 6, theme: 'carattere' },
	{ es: 'prosaico', description: 'prosaico', level: 6, theme: 'concetto' },
	{ es: 'voraz', description: 'vorace', level: 6, theme: 'concetto' },
	{ es: 'empatía', description: 'empatia', level: 6, theme: 'concetto' },
	{ es: 'irónico', description: 'ironico', level: 6, theme: 'concetto' },
	{ es: 'sobrio', description: 'sobrio', level: 6, theme: 'carattere' },
	{ es: 'pragmático', description: 'pragmatico', level: 6, theme: 'concetto' },
	{ es: 'novedoso', description: 'innovativo', level: 6, theme: 'concetto' },
	{ es: 'intrincado', description: 'complesso', level: 6, theme: 'concetto' },
	{ es: 'perplejo', description: 'perplesso', level: 6, theme: 'emozioni' },
	{ es: 'meticuloso', description: 'meticoloso', level: 6, theme: 'carattere' },
	{ es: 'tenaz', description: 'tenace', level: 6, theme: 'carattere' },
	{ es: 'trascendental', description: 'trascendentale', level: 6, theme: 'concetto' },
	{ es: 'efímero', description: 'effimero', level: 6, theme: 'concetto' },
	{ es: 'afable', description: 'affabile', level: 6, theme: 'carattere' },
	{ es: 'imparcial', description: 'imparziale', level: 6, theme: 'carattere' },
	{ es: 'efusivo', description: 'effusivo', level: 6, theme: 'carattere' }
];
	  
